# Generated by Django 6.0.5 on 2026-05-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pig", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameContent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content_text", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("extra_info", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "game_content",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="PigTask",
        ),
    ]
