# Generated by Django 6.0.5 on 2026-05-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password_hash", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        db_column="avatar_url",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
