# Generated by Django 6.0.5 on 2026-05-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AliasWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, verbose_name="Слово")),
                (
                    "category",
                    models.CharField(blank=True, default="Загальна", max_length=50),
                ),
            ],
            options={
                "db_table": "alias_words",
            },
        ),
    ]
