# Generated by Django 6.0.5 on 2026-05-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alias", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aliasword",
            options={"managed": False},
        ),
    ]
