# Generated by Django 6.0.5 on 2026-05-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alias", "0002_alter_aliasword_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="aliasword",
            table="game_content",
        ),
    ]
