# Generated by Django 6.0.5 on 2026-05-16 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dilemma", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DilemmaVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_agreed", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dilemma",
                    models.ForeignKey(
                        db_column="dilemma_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="dilemma.gamecontent",
                    ),
                ),
            ],
            options={
                "db_table": "dilemma_votes",
            },
        ),
    ]
