# Generated by Django 6.0.5 on 2026-05-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_id", models.IntegerField()),
                ("detail_text", models.TextField()),
                ("order_index", models.IntegerField()),
            ],
            options={
                "db_table": "game_detail",
                "managed": False,
            },
        ),
    ]
