# Generated by Django 6.0.5 on 2026-05-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Games",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(db_column="name", max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("rules", models.TextField(blank=True, null=True)),
                ("min_players", models.IntegerField(default=1)),
                ("has_timer", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "games",
                "managed": False,
            },
        ),
    ]
