# Generated by Django 6.0.5 on 2026-05-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_favoritegame"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="games",
            options={"managed": True},
        ),
    ]
