# Generated by Django 6.0.5 on 2026-05-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_games_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="app_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="games",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
