# Generated by Django 6.0.5 on 2026-05-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_games_app_name_games_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="games",
            options={"managed": False},
        ),
    ]
