# Generated by Django 6.0.5 on 2026-05-13 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_alter_games_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("score", models.IntegerField(default=0)),
                ("status", models.CharField(default="completed", max_length=20)),
                ("current_step", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "game_session",
                "managed": False,
            },
        ),
    ]
